name: Build NixOS disk image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-26.05
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build disk image
        run: |
          nix run nixpkgs#nixos-rebuild -- build-image \
            --flake .#kiosk \
            --image-variant raw-efi

      - name: Show image
        run: |
          find result -maxdepth 2 -type f -ls

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: nixos-kiosk-disk-image
          path: result/**
